// ─────────────────────────────────────────────────────────────
//  Praxis Core — Shared Type Definitions
// ─────────────────────────────────────────────────────────────

/** A single chat message persisted in the conversation store. */
export interface Message {
  id: string;
  conversation_id: string;
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  created_at: string;
}

/** A conversation (thread) that groups messages together. */
export interface Conversation {
  id: string;
  title: string;
  created_at: string;
}

/** Trust tiers control how aggressively the agent can act. */
export type TrustTier = 'guarded' | 'trusted' | 'always_deny';

/**
 * The verdict the permission layer returns for a given tool + tier combo.
 * - `auto_approved` — proceed without user interaction
 * - `requires_confirmation` — show a confirmation card in the UI
 * - `denied` — block execution entirely
 */
export type PermissionVerdict = 'auto_approved' | 'requires_confirmation' | 'denied';

/** A single step inside a Plan generated by the LLM planner. */
export interface PlanStep {
  tool: string;
  params: Record<string, string>;
  reasoning: string;
}

/** A multi-step plan produced by the LLM planner. */
export interface Plan {
  steps: PlanStep[];
  summary: string;
}

/** Canonical result envelope returned by every tool execution. */
export interface ToolResult {
  success: boolean;
  data: string;
  error?: string;
}

/**
 * An auditable action log entry.
 * Every tool invocation is recorded as an Action for trust & safety.
 */
export interface Action {
  id: string;
  conversation_id: string;
  tool_name: string;
  input_params_json: string;
  trust_tier: TrustTier;
  status: 'pending' | 'approved' | 'rejected' | 'completed' | 'failed';
  result_json: string;
  reasoning: string;
  created_at: string;
  resolved_at: string;
}

/** Message shape sent to the LLM API (role + content pair). */
export interface LlmMessage {
  role: string;
  content: string;
}

/** Schema for a single tool parameter used in LLM function-calling prompts. */
export interface ToolParameter {
  name: string;
  type: string;
  description: string;
  required: boolean;
}

/** Full definition of a tool: metadata + executable function. */
export interface ToolDefinition {
  name: string;
  description: string;
  parameters: ToolParameter[];
  permissionLevel: TrustTier;
  execute: (params: Record<string, string>) => Promise<ToolResult>;
}

/** Tracks retry / replan state during executor fault-tolerance loop. */
export interface RetryState {
  attempt: number;
  maxRetries: number;
  lastError: string;
  revisedPlan: Plan | null;
}

/** A user preference or learned memory fragment. */
export interface Preference {
  id: string;
  key: string;
  value: string;
  memory_type: 'semantic' | 'procedural';
  created_at: string;
}

/** A single organic search result from Serper. */
export interface SearchResult {
  title: string;
  link: string;
  snippet: string;
  position: number;
}
